### ISSUE TITLE
SageMath Symlink between docs and README are different, README produces venv errors

### ISSUE THREAD

**Issue by Spamakin** [sagemath/sage#38528] opened 2024-08-19 13:12 UTC
### Steps To Reproduce

This is in a brand new install of Sage 10.4. The [README](https://github.com/sagemath/sage/) installation instructions and the [Install from Source Code](https://doc.sagemath.org/html/en/installation/source.html#installation-steps) docs page both have different commands for producing symlinks. The expected vs actual behaviors show this with the symlinks.

Docs:
![image](https://github.com/user-attachments/assets/e5d560c6-c9ac-4cc8-ae78-6fffabc63997)
`ln -s /path/to/sage_root/sage /usr/local/bin/sage`

README:
![image](https://github.com/user-attachments/assets/c233195f-aea9-47a5-927b-03a8ffd7a139)
`$ sudo ln -s $(./sage -sh -c 'ls $SAGE_ROOT/venv/bin/sage') /usr/local/bin`

### Expected Behavior

This is what the expected behavior is, using the symlink described in step 7 of the docs:

![image](https://github.com/user-attachments/assets/aa9a51db-ddac-412e-9a91-0bc58caa401f)

### Actual Behavior

Here is what occurs upon using the symlink described in step 20 of the README:

![image](https://github.com/user-attachments/assets/5d009b23-34d5-4db0-956c-57689bff33ef)

### Environment

```markdown
- **OS**: Debian 12
- **Sage Version**: 10.7
- **Python3 Version**: 3.11.2
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by mkoeppe** [comment] 2024-08-19 17:43
These messages are not errors.

**Comment by mkoeppe** [comment] 2024-08-19 19:32
Duplicate of #38389

**Closed as not planned by mkoeppe** 2024-08-19 19:32 UTC
Labels: t: bug
