### ISSUE TITLE
Random test failure in matrix_gap

### ISSUE THREAD

**Issue by tobiasdiez** [sagemath/sage#37067] opened 2024-01-16 05:09 UTC
### Expected Behavior

Tests pass

### Actual Behavior

```
File "src/sage/matrix/matrix_gap.pyx", line 66, in sage.matrix.matrix_gap.Matrix_gap
Failed example:
    for ring in rings:
        M = MatrixSpace(ring, 2, implementation='gap')
        TestSuite(M).run(skip=['_test_construction'])
        M = MatrixSpace(ring, 2, 3, implementation='gap')
        TestSuite(M).run(skip=['_test_construction'])
Expected nothing
Got:
    #E  SET_FILT_LIST[plain list of small finite field elements][3]
    #E  SET_FILT_LIST[plain list of small finite field elements][3]
    #E  SET_FILT_LIST[plain list of small finite field elements][3]
    #E  SET_FILT_LIST[plain list of small finite field elements][3]
    #E  SET_FILT_LIST[plain list of small finite field elements][3]
    #E  SET_FILT_LIST[plain list of small finite field elements][3]
    #E  SET_FILT_LIST[plain list of small finite field elements][3]
    Failure in _test_zero:
    Traceback (most recent call last):
      File "/home/runner/work/sage/sage/src/sage/misc/sage_unittest.py", line 297, in run
        test_method(tester=tester)
      File "/home/runner/work/sage/sage/src/sage/categories/additive_magmas.py", line 688, in _test_zero
        tester.assertEqual(x + zero, x)
      File "/usr/share/miniconda3/envs/sage/lib/python3.11/unittest/case.py", line 873, in assertEqual
        assertion_func(first, second, msg=msg)
      File "/usr/share/miniconda3/envs/sage/lib/python3.11/unittest/case.py", line 866, in _baseAssertEqual
        raise self.failureException(msg)
    AssertionError: [0 2]
    [2 1] != [0 2]
    [2 1]
    ------------------------------------------------------------
    The following tests failed: _test_zero
**********************************************************************
```

### Additional Information

Only observed once so far at https://github.com/sagemath/sage/actions/runs/7450219562/job/20268638027?pr=37034

### Environment

```markdown
Conda? Linux?
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by user202729** [comment] 2024-11-09 12:21
Duplicate of https://github.com/sagemath/sage/issues/33072

**Closed as completed** 2024-11-11 03:50 UTC
Labels: t: bug
