### ISSUE TITLE
SymmetricGroup(1).gens()/.gens_small() returns empty tuple/list

### ISSUE THREAD

**Issue by Newtech66** [sagemath/sage#38311] opened 2024-06-29 17:43 UTC
### Steps To Reproduce

```
sage: SymmetricGroup(1).gens()
()
sage: SymmetricGroup(1).gens_small()
[]
```

### Expected Behavior

```
sage: S1 = SymmetricGroup(1)
sage: S1.gens()
((),)
sage: S1.gens_small()
[()]
```

### Actual Behavior

See "Steps To Reproduce".

Also, doing it likes this gives the expected behaviour:
```
sage: S1 = SymmetricGroup(1)
sage: PermutationGroup(S1.gens()).gens()
((),)
sage:PermutationGroup(S1.gens()).gens_small()
[()]
sage: PermutationGroup(S1.gens_small()).gens()
((),)
sage:PermutationGroup(S1.gens_small()).gens_small()
[()]
```

### Environment

```markdown
- **OS**: WSL 2 running on Windows 10
- **Sage Version**: 10.4.beta6
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by Newtech66** [comment] 2024-06-29 17:50
Perhaps the current behaviour is correct? Referencing this PR #36252

**Comment by DaveWitteMorris** [comment] 2024-06-29 17:56
The behaviour is correct, because the empty set does generate the trivial group.  In fact, the docstring of the `gens` method has a test to verify this output:

```
        TESTS:

        We make sure that the trivial group gets handled correctly::

            sage: SymmetricGroup(1).gens()
            ()
```
So this is not a bug.

**Comment by fchapoton** [comment] 2024-06-30 16:10
Therefore I am closing this as invalid.

**Closed as completed by fchapoton** 2024-06-30 16:10 UTC
