### ISSUE TITLE
SemistandardMultiSkewTableaux returns incorrect results

### ISSUE THREAD

**Issue by ghseeli** [sagemath/sage#36196] opened 2023-09-05 20:28 UTC
### Steps To Reproduce

Creating a list of SemistandardMultiSkewTableaux with a specified weight with more than two (skew) shapes in the tuple will generate an incorrect list of tableaux.
In particular, after the second entry, all tableaux in the tuple are just repeats entries of the second tableau, which violates the weight condition.

Here are examples to illustrate this problem.

```
sage: SemistandardMultiSkewTableaux([[[1],[0]]]*2,[1]*2).list() # correct
[[[[1]], [[2]]], [[[2]], [[1]]]]
sage: SemistandardMultiSkewTableaux([[[1],[0]]]*3,[1]*3).list() # incorrect tableaux but correct number of tableaux
[[[[1]], [[2]], [[2]]], [[[2]], [[1]], [[1]]], [[[1]], [[3]], [[3]]], [[[2]], [[3]], [[3]]], [[[3]], [[1]], [[1]]], [[[3]], [[2]], [[2]]]]
sage: for n in range(2,8):
....:    print(len(SemistandardMultiSkewTableaux([[[1],[0]]]*n,[1]*n).list())) # should be factorial(n)
2
6
24
120
720
5040
sage: SemistandardMultiSkewTableaux([[[1],[0]],[[2],[0]],[[1],[0]]],[1,1,1,1]).list() # example where shapes vary; note third shape just copies last entry of second shape.
[[[[1]], [[2, 3]], [[3]]], [[[2]], [[1, 3]], [[3]]], [[[3]], [[1, 2]], [[2]]], [[[1]], [[2, 4]], [[4]]], [[[2]], [[1, 4]], [[4]]], [[[1]], [[3, 4]], [[4]]], [[[2]], [[3, 4]], [[4]]], [[[3]], [[1, 4]], [[4]]], [[[3]], [[2, 4]], [[4]]], [[[4]], [[1, 2]], [[2]]], [[[4]], [[1, 3]], [[3]]], [[[4]], [[2, 3]], [[3]]]]
```

### Expected Behavior

The code should produce all tuples of semistandard tableaux that have the given weight.

### Actual Behavior

The code outputs an incorrect list of all such tuples of tableaux.

### Environment

```markdown
- **OS**: Cocalc Ubuntu 22.04
- **Sage Version**: 10.0
```

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by tscrim** [comment] 2023-09-07 06:22
Fixed on #36200 by updating the `pos` counter as it was intended. I used an even more simple example of three single boxes.

**Closed as completed** 2023-09-10 22:40 UTC
Labels: t: bug, c: combinatorics
