### ISSUE TITLE
Cannot define the elliptic curve

### ISSUE THREAD

**Issue by Juddd** [sagemath/sage#35828] opened 2023-06-25 10:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
- **Windows WSL2:Ubuntu 20.04**:
- **Sage Version: 10.0**:
```

### Steps To Reproduce

`EllipticCurve([-4,16]).Np(13)` will return `15` normally, but `EllipticCurve(GF(13),[-4,16])` will get a error information. Please check.

### Expected Behavior

I hope define a elliptic curve with `EllipticCurve(GF(13),[-4,16])`

### Actual Behavior

Error information tells me that this curve is singular curve

**Comment by davidtweedle** [comment] 2023-06-25 15:04
Hello.
`EllipticCurve([-4,16]).discriminant()` is divisible by 13.
So EllipticCurve([-4,16]) mod 13 does not define an elliptic curve.
On the other hand, EllipticCurve([-4,16]).Np(13) will still return values even if the curve does not have good reduction at 13.

**Comment by DaveWitteMorris** [comment] 2023-06-26 02:02
Sorry, I chose the wrong menu option. This is not a bug, so it needs to be closed as invalid ("won't fix") not "completed".

**Closed as not planned by DaveWitteMorris** 2023-06-26 02:02 UTC
Labels: t: bug
