### ISSUE TITLE
Very very slow root finding in Zmod(p^k)

### ISSUE THREAD

**Issue by grhkm21** [sagemath/sage#38840] opened 2024-10-23 08:40 UTC
### Steps To Reproduce

```python
sage: (Zmod(2^512)["x"].gen(0)^2 + 1).roots(multiplicities=False)
```

### Expected Behavior

fast using hensel lifting

### Actual Behavior

slow

### Additional Information

Also note that $x^2 + 1$ doesn't even have a root mod $2^k$ for $k \geq 2$, so if you do any kind of root lifting you would see the result is empty.

The root cause is [here](https://github.com/sagemath/sage/blob/develop/src/sage/rings/polynomial/polynomial_element.pyx#L9020-L9023) introduced by #13825. They use CRT to solve equations over IntegerModRings, but they only solve over GF(p) then *iterate over all $p^{k-1}$ cosets* to look for solutions, which is *not really optimal*.

The most direct way would be to replace that entire part with whatever the equivalent is for `(Qp(2, 512)["x"].gen(0)^2 - 1).roots()`, which by the way supports `.roots(multiplicities=True)`. But I'm not free to write the PR.

### Environment

latest version.

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by mezzarobba** [comment] 2024-10-23 09:34
Addressed by https://github.com/sagemath/sage/pull/38722 (?)

**Comment by grhkm21** [comment] 2024-10-23 10:02
Oh thanks, indeed. I will comment on that patch.

**Comment by DaveWitteMorris** [comment] 2024-10-24 18:24
I think we can close this as a duplicate of (or, more precisely, contained in) #38722.

**Closed as completed** 2024-10-25 09:02 UTC
Labels: t: bug, c: algebra
