### ISSUE TITLE
Different Monoids share the same name

### ISSUE THREAD

**Issue by tobiasdiez** [sagemath/sage#39144] opened 2024-12-16 11:06 UTC
### Steps To Reproduce

```sage
sage: F = FreeMonoid(3,'x')
sage: F
Free monoid on 3 generators (x0, x1, x2)
sage: F.rename("F")
sage: F
F
sage: G = FreeMonoid(3,'x')
sage: G
F
```

### Expected Behavior

Last call should return `Free monoid on 3 generators (x0, x1, x2)`

### Actual Behavior

Gives the name `F`

### Additional Information

Is this the expected behavior?

### Environment

Latest

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by fchapoton** [comment] 2024-12-16 16:47
And

```
sage: F is G
True
```

**Comment by mantepse** [comment] 2024-12-16 20:20
I would exactly this behavior, because F and G are the same monoid.

**Comment by user202729** [comment] 2024-12-17 03:12
Isn't this just because of the unique parent condition? In practice most people don't rename things around like this.

On the other hand… yes, this just reincorporate why things with mutable states are not a particularly good idea. Maybe we can make `M = RenamedParent(M, "M")` and somehow elements of the new parent is a wrapper around elements of the old parent, with `.parent()` changed…? Would require a massive refactor though.

**Comment by tobiasdiez** [comment] 2024-12-17 03:45
My 

> And
> 
> ```
> sage: F is G
> True
> ```

I guess this is where my confusion came from: if they have different names, then I wouldn't consider `F` and `G` to be the same anymore.

But if it's by design, then we can close this issue.

**Comment by DaveWitteMorris** [comment] 2024-12-24 00:42
`FreeMonoid` inherits from `UniqueRepresentation`:
```
class FreeMonoid(Monoid_class, UniqueRepresentation):
```
So this is the expected behaviour. I'm closing the issue.

**Closed as not planned** 2024-12-24 00:42 UTC
Labels: t: bug
