### ISSUE TITLE
Upgrade Cython to 3.0

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#35975] opened 2023-07-21 15:58 UTC
### Problem Description

currently Sage uses old Cython 0.29.*.

Meanwhile, Cython 3.0 has been released, 1st major release in 5 years or so. It comes with a lot of new features.
https://cython.readthedocs.io/en/latest/src/changes.html

### Proposed Solution

Upgrade - no idea how hard it is. Here is migration giude: https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html

### Alternatives Considered

n/a

### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

**Comment by mkoeppe** [comment] 2023-07-21 16:10
Duplicate of #29863

**Closed as not planned** 2023-07-21 16:10 UTC
Labels: t: enhancement, r: duplicate
