### ISSUE TITLE
/usr/bin/time should be a pre-req

### ISSUE THREAD

**Issue by dimpase** [sagemath/sage#37832] opened 2024-04-19 10:22 UTC
from #37785

Instead of suppressing things, just make `time` a pre-req. In particular, as it appears to cause breakage beyond warnings only, see

https://groups.google.com/g/sage-devel/c/l2MFDazkpMQ/m/_t9LFC06BAAJ
```
file:///home/pi/sage/local/var/lib/sage/venv-python3.12/var/lib/sage/wheels/cypari2-2.1.5-cp312-cp312-linux_x86_64.whl->-r
/home/pi/sage/local/var/lib/sage/venv-python3.12/var/lib/sage/scripts/cypari/spkg-requirements.txt
(line 1)) (1.11.4)
[cypari-2.1.5] [spkg-pipinst] Installing collected packages: cypari2
[cypari-2.1.5] [spkg-pipinst] Successfully installed cypari2-2.1.5
[cypari-2.1.5] [spkg-pipinst] cat: ./spkg-pipinst.time: No such file or
directory
[cypari-2.1.5] Deleting build directory
/home/pi/sage/local/var/lib/sage/venv-python3.12/var/tmp/sage/build/cypari-2.1.5
[cypari-2.1.5] Finished installing cypari-2.1.5
[cypari-2.1.5] cat: /home/pi/sage/logs/pkgs/cypari-2.1.5.time: Aucun
fichier ou dossier de ce nom
make[2]: *** [Makefile:3052 : all-build] Erreur 2
make[2] : on quitte le répertoire « /home/pi/sage/build/make » 
```

**Comment by dimpase** [comment] 2024-04-19 10:22
@tornaria @mkoeppe

**Comment by mkoeppe** [comment] 2024-04-19 18:50
@dimpase What you did in #36726 will not be repeated.

**Comment by dimpase** [comment] 2024-04-19 18:59
yes, you have proved beyond a reasonable doubt that you can replace anything with a buggy unreadable script. 

Turning Sage into Spaghettified Annoying Grossly Engineered system :-)

**Comment by tornaria** [comment] 2024-04-19 20:23
The issue is not (only) about a missing `/usr/bin/time` but also about using option `-h` which is not generally available (not on gnu time, at least).

In https://github.com/sagemath/sage/pull/37785#issuecomment-2060169117 I outlined an idea of how to use the bash builtin for `time` instead.

The fix in #37785 is not good IMO because it just disables the feature for a lot of platforms (i.e. it won't show the build time if `/usr/bin/time` is not available or does not support `-h`), but since @mkoeppe said he would work on it later, I think we can live with that.

(I'm still available to talk about it, but I can't really run the code since I don't normally build sage-the-distro, I don't even run `./configure`)

@dimpase I hope this satisfies you, if so, maybe closing this issue is a good move.

**Comment by dimpase** [comment] 2024-04-19 20:31
I opened the issue because I cannot comment on or review code in PRs opened by mkoeppe.

I think the solution there just sweeps the problem under the carpet, and this is not good.

I suppose that every system supported by Sage has /usr/bin/time, so it can be a prereq

**Comment by tornaria** [comment] 2024-04-19 20:50
> I opened the issue because I cannot comment on or review code in PRs opened by mkoeppe.

I know that is inconvenient, and I hope @mkoeppe will rethink about this, but I doubt it will happen if you keep triggering. Please, keep stating your concerns, your viewpoints, and your opposition, but in a more constructive tone (this also applies to others, each one will know... I've reported myself to sage-conduct in the past so I'm not free from mistakes either)


> I think the solution there just sweeps the problem under the carpet, and this is not good.

I agree and I said so in that PR, and I outlined a way for a better fix. Maybe an issue can be opened from my comment in the PR.

> I suppose that every system supported by Sage has /usr/bin/time, so it can be a prereq

As I said, this would not fix the problem, since the code uses `/usr/bin/time -h` which is often not available:
```
$ /usr/bin/time -h -o /dev/null true
/usr/bin/time: invalid option -- 'h'
Try '/usr/bin/time --help' for more information.
```

But please read the discussion in #37785 and feel free to create an issue from my comment to discuss further (that PR is not the place anyway since it's a temporary workaround). You can freely copy anything I said there.

**Comment by dimpase** [comment] 2024-04-20 10:16
> > I opened the issue because I cannot comment on or review code in PRs opened by mkoeppe.
> 
@tornaria 
> I know that is inconvenient, and I hope @mkoeppe will rethink about this, but I doubt it will happen if you keep triggering. Please, keep stating your concerns, your viewpoints, and your opposition, but in a more constructive tone (this also applies to others, each one will know... I've reported myself to sage-conduct in the past so I'm not free from mistakes either)

I was normally very constructive in tone and otherwise until it started to get out of hand, with @mkoeppe refused to collaborate and make any amends in his contributions. And we see the results now, not only with the voting on everything messs, but quality of reviews of his contributions going through the floor --- this `time` debacle is one of these. Indeed, it seems that `time -h` only exists on macOS, and as his contributions are waved though by a bunch of exclusive macOS users,   this was to be expected.

So this is not what I or @tobiasdiez or you got as a result of "triggering", it's what we got from someone who decided that he can get through anything he wants with a help of a gang. Until this stops, it's bound to repeat again and again.

> 
> > I think the solution there just sweeps the problem under the carpet, and this is not good.
> 
> I agree and I said so in that PR, and I outlined a way for a better fix. Maybe an issue can be opened from my comment in the PR.
> 
> > I suppose that every system supported by Sage has /usr/bin/time, so it can be a prereq
> 
> As I said, this would not fix the problem, since the code uses `/usr/bin/time -h` which is often not available:

Sure, but then `-h` can be skipped. A normal thing would be to create something like $SAGE_TIME which is `time -h` on
systems with `-h` available, and `time` on the rest of these.

**Comment by mkoeppe** [comment] 2024-04-20 20:38
Thanks @tornaria for speaking up. I appreciate it.

**Closed as completed** 2024-05-25 10:11 UTC
