### ISSUE TITLE
log(int(0), 2) hangs

### ISSUE THREAD

**Issue by katestange** [sagemath/sage#38969] opened 2024-11-14 23:19 UTC
### Steps To Reproduce

In Sage 10.5.beta6 in Jupyter notebook, or on https://sagecell.sagemath.org/ (as of today), run:
```
for i in range(1):
    floor(log(i,2))
```
and the kernel appears to hang.  

### Expected Behavior

By contrast, the supposedly equivalent command
```
floor(log(0,2))
```
gives an error `ValueError: Calling floor() on infinity or NaN` which is the expected behaviour.

### Actual Behavior

Kernel appears to hang.  Becomes unresponsive, even to user interrupt.  Must restart.

### Environment

- **OS**: Ubuntu 24.04.1 LTS
- **Sage Version**: SageMath 10.5.beta6 (from source) and also internet single cell server

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by DaveWitteMorris** [comment] 2024-11-15 00:30
Thanks for the bug report. I confirm the error (in 10.5.b9 on intel MacOS 14.8.1).

The two commands are not equivalent, because `range` returns python integers, whereas `floor(log(0,2))` is preparsed to replace `0` with `Integer(0)` so it is taking the log of a sage integer, not a python integer.  The equivalent command is `floor(log(int(0), 2))` which does hang. For a for loop that does not hang (because it uses sage integers), change `range` to `srange`.

The minimal example seems to be `log(int(0), 2)`, which puts sage into an uninterruptible hang.

**Comment by DaveWitteMorris** [comment] 2024-11-15 02:51
This is a duplicate of #37794.

**Closed as not planned by DaveWitteMorris** 2024-11-15 02:51 UTC
Labels: t: bug, p: critical / 2
