### ISSUE TITLE
Failing doctests in src/sage/modular/modform_hecketriangle

### ISSUE THREAD

**Issue by GMS103** [sagemath/sage#35273] opened 2023-03-13 17:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.

### Did you read the documentation and troubleshoot guide?

- [X] I have read the documentation and troubleshoot guide

### Environment

```markdown
- OS:  macOS (not relevant I think)
- Sage Version:  10.0.beta4
```

### Steps To Reproduce

```make ptestlong``` gives
```
sage -t --long --warn-long 56.6 --random-seed=452785398975339820822274837493975258 src/sage/modular/modform_hecketriangle/abstract_space.py  # 3 doctests failed
sage -t --long --warn-long 56.6 --random-seed=452785398975339820822274837493975258 src/sage/modular/modform_hecketriangle/readme.py  # 1 doctest failed
sage -t --long --warn-long 56.6 --random-seed=452785398975339820822274837493975258 src/sage/modular/modform_hecketriangle/space.py  # 2 doctests failed
```

### Expected Behavior

```All tests passed!```

### Actual Behavior

```
sage -t --long --warn-long 56.6 --random-seed=452785398975339820822274837493975258 src/sage/modular/modform_hecketriangle/abstract_space.py
**********************************************************************
File "src/sage/modular/modform_hecketriangle/abstract_space.py", line 1268, in sage.modular.modform_hecketriangle.abstract_space.FormsSpace_abstract.F_basis
Failed example:
    MF.F_basis(1)
Expected:
    q - 13071/(640000*d^2)*q^3 + O(q^4)
Got:
    q + (13071/(-640000*d^2))*q^3 + O(q^4)
**********************************************************************
File "src/sage/modular/modform_hecketriangle/abstract_space.py", line 1444, in sage.modular.modform_hecketriangle.abstract_space.FormsSpace_abstract.quasi_part_gens
Failed example:
    MF.quasi_part_gens(r=0)
Expected:
    [q - 34743/(640000*d^2)*q^3 + O(q^4), q^2 - 69/(200*d)*q^3 + O(q^4)]
Got:
    [q + (34743/(-640000*d^2))*q^3 + O(q^4), q^2 - 69/(200*d)*q^3 + O(q^4)]
**********************************************************************
File "src/sage/modular/modform_hecketriangle/abstract_space.py", line 1446, in sage.modular.modform_hecketriangle.abstract_space.FormsSpace_abstract.quasi_part_gens
Failed example:
    MF.quasi_part_gens(r=1)
Expected:
    [q - 9/(200*d)*q^2 + 37633/(640000*d^2)*q^3 + O(q^4),
     q^2 + 1/(200*d)*q^3 + O(q^4)]
Got:
    [q + (9/(-200*d))*q^2 + (-37633/(-640000*d^2))*q^3 + O(q^4),
     q^2 + 1/(200*d)*q^3 + O(q^4)]
**********************************************************************

sage -t --long --warn-long 56.6 --random-seed=452785398975339820822274837493975258 src/sage/modular/modform_hecketriangle/readme.py
**********************************************************************
File "src/sage/modular/modform_hecketriangle/readme.py", line 999, in sage.modular.modform_hecketriangle.readme
Failed example:
    MF.F_basis(1)
Expected:
    q - 13071/(640000*d^2)*q^3 + O(q^4)
Got:
    q + (13071/(-640000*d^2))*q^3 + O(q^4)
**********************************************************************

sage -t --long --warn-long 56.6 --random-seed=452785398975339820822274837493975258 src/sage/modular/modform_hecketriangle/space.py
**********************************************************************
File "src/sage/modular/modform_hecketriangle/space.py", line 399, in sage.modular.modform_hecketriangle.space.QuasiCuspForms.gens
Failed example:
    MF.gens()
Expected:
    [q - 17535/(262144*d^2)*q^3 + O(q^4),
     q^2 - 47/(128*d)*q^3 + O(q^4),
     q - 9/(128*d)*q^2 + 15633/(262144*d^2)*q^3 + O(q^4),
     q^2 - 7/(128*d)*q^3 + O(q^4),
     q - 23/(64*d)*q^2 - 3103/(262144*d^2)*q^3 + O(q^4),
     q - 3/(64*d)*q^2 - 4863/(262144*d^2)*q^3 + O(q^4),
     q - 27/(64*d)*q^2 + 17217/(262144*d^2)*q^3 + O(q^4)]
Got:
    [q + (17535/(-262144*d^2))*q^3 + O(q^4),
     q^2 - 47/(128*d)*q^3 + O(q^4),
     q + (9/(-128*d))*q^2 + (-15633/(-262144*d^2))*q^3 + O(q^4),
     q^2 - 7/(128*d)*q^3 + O(q^4),
     q - 23/(64*d)*q^2 - 3103/(262144*d^2)*q^3 + O(q^4),
     q - 3/(64*d)*q^2 - 4863/(262144*d^2)*q^3 + O(q^4),
     q - 27/(64*d)*q^2 + 17217/(262144*d^2)*q^3 + O(q^4)]
**********************************************************************
File "src/sage/modular/modform_hecketriangle/space.py", line 817, in sage.modular.modform_hecketriangle.space.CuspForms.gens
Failed example:
    MF.gens()
Expected:
    [q + 296888795/(10319560704*d^3)*q^4 + O(q^5),
     q^2 + 6629/(221184*d^2)*q^4 + O(q^5),
     q^3 - 25/(96*d)*q^4 + O(q^5)]
Got:
    [q + 296888795/(10319560704*d^3)*q^4 + O(q^5),
     q^2 + (-6629/(-221184*d^2))*q^4 + O(q^5),
     q^3 - 25/(96*d)*q^4 + O(q^5)]
**********************************************************************
```

### Additional Information

Why plus/minus signs are not simplified in fractions?

**Comment by jhpalmieri** [comment] 2023-03-16 17:58
Perhaps caused be #35045.

**Comment by jhpalmieri** [comment] 2023-03-20 22:30
Marking as a blocker since we get failing doctests.

**Comment by mezzarobba** [comment] 2023-03-21 09:00
(Replying to https://github.com/sagemath/sage/pull/35045#issuecomment-1477092175:)

I don't see how something like that can be platform-dependent. Have you compared the parents of the output on Linux and OSX, or checked if manually created expressions in the same parent failed to simplify too?

**Comment by mezzarobba** [comment] 2023-03-21 15:52
> If I do `a = MF.F_basis(1)`, then `parent(a)` and `type(a)` are the same on OS X and Linux, but their print representations are different.

What about the parent of `a.q_expansion()`? Is it `Power Series Ring in q over Fraction Field of Univariate Polynomial Ring in d over Integer Ring` as on Linux, or something different (e.g., `... over RationalField`)? How do the print representations of manually created elements of that parent look like? of its base ring?

**Comment by jhpalmieri** [comment] 2023-03-21 16:09
For both platforms, I see the same behavior:

```
sage: R = parent(a.q_expansion())
sage: R
sage: R.base_ring().inject_variables()
Defining d
sage: R(1/(-d))
1/-d

sage: R.inject_variables()
Defining q
sage: q + (13071/(-640000*d^2))*q^3
q + (13071/(-640000*d^2))*q^3

```
At least on OS X I see the same behavior in vanilla 10.0.beta3 —  without the branch at #35045. (I haven't tried on linux.)

**Comment by jhpalmieri** [comment] 2023-03-22 00:25
Maybe it's Singular. When I use `./configure --with-system-singular=no`, tests pass. On OS X, Homebrew includes Singular 4.3.2, whereas Sage includes 4.3.1.

**Comment by mezzarobba** [comment] 2023-03-22 07:35
> The last two expressions evaluate as equal, so why don't they print the same way?

Sounds like https://github.com/sagemath/sage/issues/35221#issuecomment-1470030998, but I don't understand why the issue occurs on some systems only then.

> Maybe #35045 just changed how the expression is defined

Yes, most probably.

**Comment by mezzarobba** [comment] 2023-03-22 07:38
> Maybe it's Singular. When I use `./configure --with-system-singular=no`, tests pass. On OS X, Homebrew includes Singular 4.3.2, whereas Sage includes 4.3.1.

Ok: not a bug, then?

**Comment by jhpalmieri** [comment] 2023-03-22 16:05
It causes doctests to fail, so it needs to be fixed.

**Comment by mezzarobba** [comment] 2023-03-22 16:19
Maybe... It is quite common to see a few failing doctests when using system packages for dependencies like pari, gap, or singular. I tend to view that as normal, though I agree that ideally it should be fixed (if we can do it by adapting the code or the tests, not by restricting the range of allowed versions of the dependency when the version for which the tests fail works fine otherwise).

**Comment by GMS103** [comment] 2023-03-22 16:27
Whatever the cause, I do not see any reason to get
```q + (13071/(-640000*d^2))*q^3 + O(q^4)```
instead of
```q - 13071/(640000*d^2)*q^3 + O(q^4)```.
This seems to me incoherent (when compared for instance with ```q^2 - 47/(128*d)*q^3 + O(q^4)```).
Is it difficult to correct?

**Comment by mezzarobba** [comment] 2023-03-22 18:56
> Is it difficult to correct?

Even if the difference in behavior between systems observed here is due to different versions of Singular, the fact that fractions are not normalized as one would expect looks a lot like the issue discussed in https://github.com/sagemath/sage/issues/35221#issuecomment-1470030998.

**Comment by jhpalmieri** [comment] 2023-03-22 20:35
A potential fix: replace doctests like
```
sage: MF.F_basis(1)
q - 13071/(640000*d^2)*q^3 + O(q^4)
```
with
```
sage: MF.F_basis(1) == q - 13071/(640000*d^2)*q^3 + O(q^4)
True
```
This is not altogether satisfying because I agree that we should see `- 13071/(640000*d^2)` rather than `13071/(-640000*d^2)`. But it would test the mathematics correctly.

**Comment by jhpalmieri** [comment] 2023-04-14 03:50
I tried creating some doctests of the form I mentioned in the previous comment, but I was unsuccessful. If someone else wants to try, I'm happy to test.

**Comment by vbraun** [comment] 2023-05-14 08:57
The doctests all have properly normalized fractions, so the fact that they aren't is imho indicative of a bigger problem and we shouldn't "fix" it by allowing the wrong normalization. We do have multiple OSX buildbots and they don't reproduce the issue, so its a Singular 4.3.2 bug or a bug in homebrew's packaging. Either way, it shouldn't block us from making a release.

**Comment by mezzarobba** [comment] 2023-05-14 09:17
This is just a guess, but I think: (1) there *is* a bigger problem, namely that rational fractions are not properly normalized in Sage *in general*; (2) but that problem is known and documented in other issues and the fact that it pops up here is an accident.

**Comment by jhpalmieri** [comment] 2023-06-22 18:41
Should we disallow this version of the system Singular?

**Comment by GMS103** [comment] 2023-07-09 21:12
This issue seems related to Homebrew's Singular version 4.3.2p2, as it does not appear with Singular SPKG version 4.3.1p3.  See https://github.com/sagemath/sage/issues/35833.

**Comment by mkoeppe** [comment] 2023-07-11 19:42
The same version built from the updated SPKG (#35934) passes the tests.

The difference with the homebrew formula https://github.com/Homebrew/homebrew-core/blob/master/Formula/singular.rb#L56 is that we build Singular with FLINT.

**Comment by mkoeppe** [comment] 2023-07-11 20:12
We could for example reject system singular if it does not use FLINT.
that's `HAVE_FLINT` in <singular/singularconfig.h>

**Comment by mkoeppe** [comment] 2023-07-11 20:21
Upstream does not test configurations without FLINT, it seems: https://github.com/Singular/Singular/blob/spielwiese/.github/workflows/runtests.yml#L15

**Closed as completed** 2023-09-01 20:18 UTC
Labels: t: bug, c: modular forms
