### ISSUE TITLE
one doctest in klyachko.py fails with --random-seed=129460391319295326288131905864879221787

### ISSUE THREAD

**Issue by seblabbe** [sagemath/sage#35391] opened 2023-03-30 08:40 UTC
The command
```
sage -t --long src/sage/schemes/toric/sheaf/klyachko.py
```
works fine:
```
sage -t --long --random-seed=179332351499309459115246830257894613841 src/sage/schemes/toric/sheaf/klyachko.py
    [151 tests, 5.66 s]
----------------------------------------------------------------------
All tests passed!
----------------------------------------------------------------------
Total time for all tests: 5.7 seconds
```
but here is a seed for which it fails:
```
sage -t --long --random-seed=129460391319295326288131905864879221787 src/sage/schemes/toric/sheaf/klyachko.py
**********************************************************************
File "src/sage/schemes/toric/sheaf/klyachko.py", line 951, in sage.schemes.toric.sheaf.klyachko.KlyachkoBundle_class.random_deformation
Failed example:
    Vtilde.cohomology(dim=True, weight=(0,))
Expected:
    (1, 0)
Got:
    (0, 0)
**********************************************************************
1 item had failures:
   1 of   7 in sage.schemes.toric.sheaf.klyachko.KlyachkoBundle_class.random_deformation
    [151 tests, 1 failure, 5.84 s]
----------------------------------------------------------------------
sage -t --long --random-seed=129460391319295326288131905864879221787 src/sage/schemes/toric/sheaf/klyachko.py  # 1 doctest failed
----------------------------------------------------------------------
```

**Comment by mkoeppe** [comment] 2023-03-30 11:42
Duplicate of #32773

**Comment by seblabbe** [comment] 2023-03-30 11:52
Ok, sorry for the duplicate. Also I should say that this was while running tests on sagemath version 9.8.rc0.
After upgrading to 10.0.beta6, I can't reproduce the error with that seed on the same machine.

**Closed as not planned** 2023-03-30 11:53 UTC
Labels: r: duplicate
