### ISSUE TITLE
Test in schemes/elliptic_curves/ell_rational_field.py raises RuntimeError for some random seed

### ISSUE THREAD

**Issue by cyrilbouvier** [sagemath/sage#39052] opened 2024-11-28 19:32 UTC
### Steps To Reproduce

```
sage -t --warn-long 5.0 --random-seed=44632971204031729886770251021771496554 src/sage/schemes/elliptic_curves/ell_rational_field.py
```

### Expected Behavior

```py
...
----------------------------------------------------------------------
All tests passed!
----------------------------------------------------------------------
...
```

### Actual Behavior

```py
...
**********************************************************************
File "src/sage/schemes/elliptic_curves/ell_rational_field.py", line 2392, in sage.schemes.elliptic_curves.ell_rational_field.EllipticCurve_rational_field.?
Failed example:
    E.gens(use_database=False, algorithm='pari',pari_effort=4)   # random
Exception raised:
    Traceback (most recent call last):
      File "/home/cyril/src/sage-dev/src/sage/doctest/forker.py", line 716, in _run
        self.compile_and_execute(example, compiler, test.globs)
      File "/home/cyril/src/sage-dev/src/sage/doctest/forker.py", line 1137, in compile_and_execute
        exec(compiled, globs)
      File "<doctest sage.schemes.elliptic_curves.ell_rational_field.EllipticCurve_rational_field.?[4]>", line 1, in <module>
        E.gens(use_database=False, algorithm='pari',pari_effort=Integer(4))   # random
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/cyril/src/sage-dev/src/sage/schemes/elliptic_curves/ell_rational_field.py", line 2353, in gens
        gens, proved = self._compute_gens(proof, **kwds)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/cyril/src/sage-dev/src/sage/schemes/elliptic_curves/ell_rational_field.py", line 2467, in _compute_gens
        raise RuntimeError(f"generators could not be determined. So far we found {ge}. Hint: increase pari_effort.")
    RuntimeError: generators could not be determined. So far we found []. Hint: increase pari_effort.
**********************************************************************
1 item had failures:
   1 of  95 in sage.schemes.elliptic_curves.ell_rational_field.EllipticCurve_rational_field.?
    [884 tests, 1 failure, 20.36s wall]

...
```

### Additional Information

Every other values of random seed that I tried work, so it seems to be a very rare event.

I am not sure if it is a Sage bug or a Pari bug as it happens in a function call with a parameter `algorithm='pari'`

### Environment

- **OS**:  Debian
- **Sage Version**: 10.5rc1

### Checklist

- [X] I have searched the existing issues for a bug report that matches the one I want to file, without success.
- [X] I have read the documentation and troubleshoot guide

**Comment by DaveWitteMorris** [comment] 2024-11-28 23:42
Duplicate of #38813.

**Closed as not planned by DaveWitteMorris** 2024-11-28 23:42 UTC
Labels: t: bug, c: elliptic curves
